// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: arrangements.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getArrangementWithSongId = `-- name: GetArrangementWithSongId :many
SELECT name, lyrics, chord_chart, id, pc_id, chord_chart_key, has_chord_chart, has_chords, song_id FROM arrangements 
WHERE song_id = $1
`

func (q *Queries) GetArrangementWithSongId(ctx context.Context, songID uuid.UUID) ([]Arrangement, error) {
	rows, err := q.db.QueryContext(ctx, getArrangementWithSongId, songID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Arrangement
	for rows.Next() {
		var i Arrangement
		if err := rows.Scan(
			&i.Name,
			&i.Lyrics,
			&i.ChordChart,
			&i.ID,
			&i.PcID,
			&i.ChordChartKey,
			&i.HasChordChart,
			&i.HasChords,
			&i.SongID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
