// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Arrangement struct {
	Name          string
	Lyrics        string
	ChordChart    sql.NullString
	ID            uuid.UUID
	PcID          sql.NullInt32
	ChordChartKey sql.NullString
	HasChordChart sql.NullBool
	HasChords     sql.NullBool
	SongID        uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Event struct {
	ID        uuid.UUID
	Name      string
	Date      time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
}

type EventsArrangement struct {
	EventID       uuid.UUID
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ArrangementID uuid.UUID
}

type Song struct {
	PcID       sql.NullInt32
	Admin      sql.NullString
	Author     sql.NullString
	CcliNumber sql.NullInt32
	CopyRight  sql.NullString
	Themes     sql.NullString
	Title      string
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID             uuid.UUID
	FirstName      string
	LastName       string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	PcAuthorized   bool
	Avatar         sql.NullString
	PcID           sql.NullInt32
}

type UsersSong struct {
	ID     uuid.UUID
	UserID uuid.UUID
	SongID uuid.UUID
}
