// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: songs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getSongById = `-- name: GetSongById :one
SELECT id, pc_id, admin, author, ccli_number, copy_right, themes, title, user_id FROM songs
WHERE id = $1
`

func (q *Queries) GetSongById(ctx context.Context, id uuid.UUID) (Song, error) {
	row := q.db.QueryRowContext(ctx, getSongById, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.PcID,
		&i.Admin,
		&i.Author,
		&i.CcliNumber,
		&i.CopyRight,
		&i.Themes,
		&i.Title,
		&i.UserID,
	)
	return i, err
}
